title: Sunplate Toolkit
baseurl: https://anonx.github.io/sunplate

menu:
  about:
    name: About
    url: /
    icon: sun
  manual:
    name: Manual
    url: /manual/index.html
    icon: book
  tracker:
    name: Issue Tracker
    uri: https://github.com/anonx/sunplate/issues
    icon: bug

manual:
  -
    name: Introduction
    url: /manual/index.html
    icon: file text
    category: manual
  -
    name: sunplate create
    url: /manual/create/index.html
    icon: cube
    category: create
  -
    name: sunplate run
    url: /manual/run/index.html
    icon: cube
    category: run
  -
    name: sunplate generate handlers
    url: /manual/handlers/index.html
    icon: cube
    category: handlers
    pages:
      -
        name: Controllers
        url: /manual/handlers/controllers.html
      -
        name: Actions
        url: /manual/handlers/actions.html
  -
    name: Deployment
    url: /manual/deployment.html
    icon: file text

safe: true
lsi: false
markdown: redcarpet
highligher: pygments
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - with_toc_data
    - emphasis
    - double_emphasis
    - quote
