title: Sunplate Toolkit
url: https://anonx.github.io/sunplate

safe: true
lsi: false
markdown: redcarpet
highligher: pygments
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - with_toc_data
    - emphasis
    - double_emphasis
    - quote
